# Generated by Django 4.0.3 on 2022-08-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0006_remove_banner_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=22, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=22, verbose_name='Familiya')),
                ('email', models.EmailField(max_length=45, verbose_name='email')),
                ('phone', models.CharField(max_length=13, verbose_name='phone')),
                ('adress_1', models.CharField(max_length=99, verbose_name='adress_1')),
                ('adress_2', models.CharField(blank=True, max_length=99, verbose_name='adress_1')),
                ('country', models.CharField(choices=[('uzbekistan ', 'uzbekistan'), ('kirgistan', 'kirgistan'), ('rus', 'rus')], max_length=99, verbose_name='davlat')),
                ('city', models.CharField(max_length=99, verbose_name='kocha')),
                ('street', models.CharField(max_length=99, verbose_name='kocha')),
                ('zip_code', models.PositiveIntegerField(verbose_name='POCHTAINDEKSI')),
                ('status', models.CharField(choices=[(1, 'created'), (2, 'on_process'), (3, 'fineshed'), (0, 'cencelled')], max_length=99, verbose_name='Buyurtma holati')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
